// <auto-generated />
using System;
using BCRA_API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BCRA_API.Migrations
{
    [DbContext(typeof(SQLiteContext))]
    partial class SQLiteContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("BCRA_API.Model.Movimientos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CuentaAcreedora")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CuentaDeudora")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EntidadAcreedora")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EntidadDeudora")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaProcesado")
                        .HasColumnType("TEXT");

                    b.Property<float>("Importe")
                        .HasColumnType("REAL");

                    b.Property<string>("InstruccionDePago")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NumeroInterno")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Operatoria")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Transaccion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Movimientos");
                });
#pragma warning restore 612, 618
        }
    }
}
